### ISSUE TITLE
想学习一下，有个小问题

### ISSUE THREAD

**Issue by Invoker-liu** [nbfujx/Goku.Framework.CoreUI#1]
粗看了下文件夹，发现有iml 文件，这不是idea生成的文件吗？会不会影响编译？笔者有空的话，麻烦回复下，谢谢

**Comment by nbfujx** [comment]
直接拷贝下src和pom.xml文件就好了，其他是idea生成的文件

**Comment by Invoker-liu** [comment]
好的，谢谢
